# See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
# Also: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables

name: 'Actions Tagger'
author: 'smac89'
description:
  'Keep your action versions up-to-date by automatically promoting a major
  version each time a minor release is created'
inputs:
  # TODO v3: remove this
  publish_latest_tag:
    description: '(Deprecated) Whether or not to also publish a `latest` tag'
    required: false
    default: false
  publish_latest:
    description:
      'Whether or not to also publish a `latest` ref (depending on
      `prefer_branch_releases`)'
    required: false
    default: false
  prefer_branch_releases:
    description:
      'Do you prefer creating major branches as opposed to major tags?'
    required: false
    default: false
  token:
    description: "A GitHub token used for making requests to Github's API"
    default: ${{ github.token }}
outputs:
  tag:
    description: 'The major version that was created/updated. ex v1'
  latest:
    description:
      "Either 'true' or 'false' depending on whether the 'latest' tag was
      created"
runs:
  using: 'node20'
  main: 'lib/index.js'
branding:
  icon: 'tag'
  color: 'white'
