
# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: weekly
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: ">12"
    automerged_updates:
      - match:
          dependency_type: development
          update_type: "all"
    commit_message:
      prefix: "chore"
      include_scope: true
