name: Sanity Check

on:
  pull_request:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: jest
        run: |
          yarn --frozen-lockfile
          yarn test
