name: Sanity Check

on:
  pull_request:
  push:
    branches:
      - 'release/**'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'jest'
        run: |
          npm install
          npm run test
